config/routes.rb
Rails.application.routes.draw do
  resources :insta_posts do
    collection do
      post :import
    end
  end
  

  resources :comments
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "comments#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/insta_post.rb
class InstaPost < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = {hello: 'hello'}
    
    render json: @comments
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:name, :body)
    end
end

app/controllers/insta_posts_controller.rb
class InstaPostsController < ApplicationController
  require 'csv'
  before_action :set_insta_post, only: %i[ show edit update destroy ]
  def import
    file = params['file']
    if file
     redirect_to root_path, notice: 'Only CSV, please!' unless file.content_type =='text/csv'
     file = File.open(file)
     csv=CSV.parse(file, headers: :true)
     csv.each do |row|
      insta_post_hash={}
      insta_post_hash[:id_media]=row['id']
      insta_post_hash[:like_count]=row['like_count']
      insta_post_hash[:media_type]=row['media_type']
      insta_post_hash[:comments_count]=row['comments_count']
      insta_post_hash[:timestamp]=row['timestamp']
      insta_post_hash[:media_url]=row['media_url']
      InstaPost.create(insta_post_hash)
     end
     redirect_to insta_posts_path
     #binding.b
    end
  end
  # GET /insta_posts or /insta_posts.json
  def index
    date_start=params[:date_start]
    date_end=params[:date_end]

    if date_start && date_end
        @insta_posts = InstaPost.where(timestamp: (Date.parse(date_start)..Date.parse(date_end)))
        render json: @insta_posts
    else
      @insta_posts= InstaPost.all.limit(10)
      render json: @insta_posts

    end
  end

  # GET /insta_posts/1 or /insta_posts/1.json
  def show
  end

  # GET /insta_posts/new
  def new
    @insta_post = InstaPost.new
  end

  # GET /insta_posts/1/edit
  def edit
  end

  # POST /insta_posts or /insta_posts.json
  def create
    @insta_post = InstaPost.new(insta_post_params)

    respond_to do |format|
      if @insta_post.save
        format.html { redirect_to insta_post_url(@insta_post), notice: "Insta post was successfully created." }
        format.json { render :show, status: :created, location: @insta_post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @insta_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /insta_posts/1 or /insta_posts/1.json
  def update
    respond_to do |format|
      if @insta_post.update(insta_post_params)
        format.html { redirect_to insta_post_url(@insta_post), notice: "Insta post was successfully updated." }
        format.json { render :show, status: :ok, location: @insta_post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @insta_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /insta_posts/1 or /insta_posts/1.json
  def destroy
    @insta_post.destroy

    respond_to do |format|
      format.html { redirect_to insta_posts_url, notice: "Insta post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_insta_post
      @insta_post = InstaPost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def insta_post_params
      params.require(:insta_post).permit(:like_count, :media_type, :media_url, :timestamp, :comments_count, :id_media, :impressions, :reach)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/insta_posts_helper.rb
module InstaPostsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <strong>Name:</strong>
    <%= comment.name %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= comment.body %>
  </p>

</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>

  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>

app/views/insta_posts/_form.html.erb
<%= form_with(model: insta_post) do |form| %>
  <% if insta_post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(insta_post.errors.count, "error") %> prohibited this insta_post from being saved:</h2>

      <ul>
        <% insta_post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :like_count, style: "display: block" %>
    <%= form.number_field :like_count %>
  </div>

  <div>
    <%= form.label :media_type, style: "display: block" %>
    <%= form.text_field :media_type %>
  </div>

  <div>
    <%= form.label :media_url, style: "display: block" %>
    <%= form.text_area :media_url %>
  </div>

  <div>
    <%= form.label :timestamp, style: "display: block" %>
    <%= form.date_field :timestamp %>
  </div>

  <div>
    <%= form.label :comments_count, style: "display: block" %>
    <%= form.number_field :comments_count %>
  </div>

  <div>
    <%= form.label :id_media, style: "display: block" %>
    <%= form.number_field :id_media %>
  </div>

  <div>
    <%= form.label :impressions, style: "display: block" %>
    <%= form.number_field :impressions %>
  </div>

  <div>
    <%= form.label :reach, style: "display: block" %>
    <%= form.number_field :reach %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/insta_posts/_insta_post.html.erb
<div id="<%= dom_id insta_post %>">
  <p>
    <strong>Like count:</strong>
    <%= insta_post.like_count %>
  </p>

  <p>
    <strong>Media type:</strong>
    <%= insta_post.media_type %>
  </p>

  <p>
  <% if insta_post.media_url%>
    <strong>Media url:</strong>
    <%= insta_post.media_url%>
    <%end%>
  </p>

  <p>
    <strong>Timestamp:</strong>
    <%= insta_post.timestamp %>
  </p>

  <p>
    <strong>Comments count:</strong>
    <%= insta_post.comments_count %>
  </p>

  <p>
    <strong>Id media:</strong>
    <%= insta_post.id_media %>
  </p>

  <p>
    <strong>Impressions:</strong>
    <%= insta_post.impressions %>
  </p>

  <p>
    <strong>Reach:</strong>
    <%= insta_post.reach %>
  </p>

</div>

app/views/insta_posts/edit.html.erb
<h1>Editing insta post</h1>

<%= render "form", insta_post: @insta_post %>

<br>

<div>
  <%= link_to "Show this insta post", @insta_post %> |
  <%= link_to "Back to insta posts", insta_posts_path %>
</div>

app/views/insta_posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Insta posts</h1>
<%= form_with url: insta_posts_path, method: :get do |f|  %>
  <%=f.label :date_start %>
  <%=f.date_field :date_start %>
  <%=f.label :date_end %>
  <%=f.date_field :date_end %>
  <%=f.submit%>
<%end%>
<div id="insta_posts">
  <% @insta_posts.each do |insta_post| %>
    <%= render insta_post %>
    <p>
      <%= link_to "Show this insta post", insta_post %>
    </p>
  <% end %>
</div>

<%= link_to "New insta post", new_insta_post_path %>

app/views/insta_posts/new.html.erb
<h1>New insta post</h1>

<%= render "form", insta_post: @insta_post %>

<br>
<div>
<h3> Import CSV file for Instagram posts format csv</h3>
   <%= form_with url: import_insta_posts_path , method: :post do |f| %>
    <%=f.file_field :file, accept: '.csv' %>
    <%= f.submit 'Import' %>
    <%end%>
</div>
<div>
  <%= link_to "Back to insta posts", insta_posts_path %>
</div>

app/views/insta_posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @insta_post %>

<div>
  <%= link_to "Edit this insta post", edit_insta_post_path(@insta_post) %> |
  <%= link_to "Back to insta posts", insta_posts_path %>

  <%= button_to "Destroy this insta post", @insta_post, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DashboardApiV2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>